markdown: kramdown
highlighter: pygments
permalink: /:categories/:year-:month-:day/:title.html
paginate_path: page/:num

blog:
    name : Simple Blog
    description : 温暖岁月,惊艳时光
    title : Simple Blog - 董玉玺的个人博客
    url : http://dongyuxi.github.io
author:
    name : 董玉玺
    email : orange2010road@gmail.com
    weibo : http://weibo.com/orange2010road
    github : https://github.com/dongyuxi
